/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function ErosionPlane(props) {
  const { nodes, materials } = useGLTF("/erosi0n_plane.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ground.geometry}
        material={materials.Material}
      />
    </group>
  );
}

useGLTF.preload("/ersoin_plane.glb");
