/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Ipay (https://sketchfab.com/ipay)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/soil-profile-84554828171243a8be5cef86ef284fcf
Title: Soil Profile
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';
import * as THREE from 'three';

//useGLTF('3D-models/soil/soil_profile/scene.gltf')

export function Soil(props) {
  const { nodes, materials } = useGLTF('3D-models/soil/soil_profile/scene.gltf')

  const groupRef = useRef(null); // Create a ref for the group

  // Use useFrame to rotate the model continuously
  useFrame(() => {
    if (groupRef.current) {
      groupRef.current.rotation.y += 0.01; // Rotate around the Y-axis
    }
  });

  return (
    <group
    ref={groupRef}
    {...props} dispose={null}>
      <group position={[-0.241, 1.772, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials['Material.034']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials['Material.034']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials['Material.034']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials['Material.034']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8.geometry}
          material={materials['Material.033']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9.geometry}
          material={materials['Material.033']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_11.geometry}
        material={materials['Material.036']}
        position={[3, 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_13.geometry}
        material={materials.Material}
        position={[0.007, 0.998, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_15.geometry}
        material={materials['Material.001']}
        position={[0.007, 0.02, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_17.geometry}
        material={materials['Material.002']}
        position={[0.007, 2.028, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_19.geometry}
        material={materials.Color_D09_1}
        position={[0.007, 1.621, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_21.geometry}
        material={materials.Color_005_1}
        position={[0.007, 2, 0]}
        scale={[1, 0.094, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_23.geometry}
        material={materials['Material.005']}
        position={[0.007, 2.021, 0]}
      />
    </group>
  )
}