/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: matousekfoto (https://sketchfab.com/matousekfoto)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cherry-tree-232e1f60165342afb09a40230f7a469d
Title: Cherry tree
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function CherryTree(props) {
  const { nodes, materials } = useGLTF("3D-models/cherry-tree/scene.gltf");
  return (
    <group {...props} dispose={null} scale={3}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.001}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.meshNode_Material_u1_v1_0.geometry}
              material={materials.Material_u1_v1}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.meshNode_Material_u2_v1_0.geometry}
              material={materials.Material_u2_v1}
            />
          </group>
        </group>
      </group>
    </group>
  );
}
