@startmindmap
* Main Page
** Administración
*** Gestión de Usuarios
**** Ver Usuarios Registrados
**** Editar Usuarios
**** Eliminar Usuarios
*** Datos de Uso de la Aplicación
** Notificaciones
*** Novedades y Actividades Nuevas
*** Configuración de Notificaciones
** Información del Usuario
*** Configuración de Perfil
*** Historial de Actividades
@endmindmap